### ISSUE TITLE
When I run show_label.py to show drivable area,it reports error ,what should I do?

### ISSUE THREAD

**Issue by gittigxuy** [ucbdrive/bdd-data#15]
Image: 06583aaf-bb7d4ce1.jpg
Traceback (most recent call last):
  File "/home/xuy/.pyenv/versions/3.6.1/lib/python3.6/site-packages/matplotlib/colors.py", line 166, in to_rgba
    rgba = _colors_full_map.cache[c, alpha]
KeyError: ((0.00392156862745098, 1.003921568627451, 0.011764705882352941), None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xuy/code/bdd-data/bdd_data/show_labels.py", line 847, in <module>
    main()
  File "/home/xuy/code/bdd-data/bdd_data/show_labels.py", line 843, in main
    viewer.view()
  File "/home/xuy/code/bdd-data/bdd_data/show_labels.py", line 551, in view
    self.write()
  File "/home/xuy/code/bdd-data/bdd_data/show_labels.py", line 584, in write
    if self.show_image():
  File "/home/xuy/code/bdd-data/bdd_data/show_labels.py", line 677, in show_image
    self.draw_drivable(objects)
  File "/home/xuy/code/bdd-data/bdd_data/show_labels.py", line 744, in draw_drivable
    alpha=alpha, color=color))
  File "/home/xuy/code/bdd-data/bdd_data/show_labels.py", line 721, in poly2patch
    antialiased=False, snap=True)
  File "/home/xuy/.pyenv/versions/3.6.1/lib/python3.6/site-packages/matplotlib/patches.py", line 927, in __init__
    Patch.__init__(self, **kwargs)
  File "/home/xuy/.pyenv/versions/3.6.1/lib/python3.6/site-packages/matplotlib/patches.py", line 87, in __init__
    self.set_edgecolor(edgecolor)
  File "/home/xuy/.pyenv/versions/3.6.1/lib/python3.6/site-packages/matplotlib/patches.py", line 295, in set_edgecolor
    self._set_edgecolor(color)
  File "/home/xuy/.pyenv/versions/3.6.1/lib/python3.6/site-packages/matplotlib/patches.py", line 283, in _set_edgecolor
    self._edgecolor = colors.to_rgba(color, self._alpha)
  File "/home/xuy/.pyenv/versions/3.6.1/lib/python3.6/site-packages/matplotlib/colors.py", line 168, in to_rgba
    rgba = _to_rgba_no_colorcycle(c, alpha)
  File "/home/xuy/.pyenv/versions/3.6.1/lib/python3.6/site-packages/matplotlib/colors.py", line 229, in _to_rgba_no_colorcycle
    raise ValueError("RGBA values should be within 0-1 range")
ValueError: RGBA values should be within 0-1 range

**Comment by fyu** [comment]
Do you still have this problem? Are you in sync with master? I can not find the right line of code based on your stack trace.
