### ISSUE TITLE
when I use your evaluate.py，I encounter some question

### ISSUE THREAD

**Issue by gittigxuy** [ucbdrive/bdd-data#16]
my gt file is bdd100k_labels_images_val.json,and my result file is my predict file.but I get some error.

###################

Traceback (most recent call last):
  File "/home/xuy/code/bdd-data/bdd_data/evaluate.py", line 211, in <module>
    main()
  File "/home/xuy/code/bdd-data/bdd_data/evaluate.py", line 204, in main
    mean, breakdown = evaluate_detection(args.gt, args.result)
  File "/home/xuy/code/bdd-data/bdd_data/evaluate.py", line 182, in evaluate_detection
    cat_gt = group_by_key(gt, 'category')
  File "/home/xuy/code/bdd-data/bdd_data/evaluate.py", line 103, in group_by_key
    groups[d[key]].append(d)
KeyError: 'category'
######################
what should I do?Thanks

**Comment by gittigxuy** [comment]
I find the reason,I should use detection_train.json instead of bdd100k_labels_images_val.json
