### ISSUE TITLE
show_labels.py: error: the following arguments are required: -l/--label

### ISSUE THREAD

**Issue by EvaneSnow** [ucbdrive/bdd-data#56]
when I run python3 -m bdd_data.show_labels --image-dir bdd100k/images/100k/train-l bdd100k/labels/bdd100k_labels_images_train.json, and have a error:
usage: show_labels.py [-h] [-i IMAGE] [--image-dir IMAGE_DIR] -l LABEL
                      [-s SCALE] [--no-attr] [--no-lane] [--no-drivable]
                      [--no-box2d] [-o OUTPUT_DIR] [--instance] [--drivable]
                      [--target-objects TARGET_OBJECTS] [--format FORMAT]
show_labels.py: error: the following arguments are required: -l/--label
can you help me, thanks

**Comment by sabipeople** [comment]
you miss space before -l option
your command: 
--image-dir bdd100k/images/100k/train-l bdd100k/labels/bdd100k_labels_images_train.json
shoud be :
--image-dir bdd100k/images/100k/train -l bdd100k/labels/bdd100k_labels_images_train.json
something like this. 
you have missed a space.

**Comment by EvaneSnow** [comment]
@sabipeople : I have try it, but it's error:
python3 -m bdd_data.show_labels --image-dir bdd100k/images/100k/train -l bdd100k/labels/bdd100k_labels_images_train.json
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/media/snow/Snow/bdd-data/bdd_data/show_labels.py", line 881, in <module>
    main()
  File "/media/snow/Snow/bdd-data/bdd_data/show_labels.py", line 876, in main
    viewer = LabelViewer2(args)
  File "/media/snow/Snow/bdd-data/bdd_data/show_labels.py", line 542, in __init__
    self.label = read_labels(self.label_paths[self.file_index])
  File "/media/snow/Snow/bdd-data/bdd_data/show_labels.py", line 481, in read_labels
    labels = json.load(open(label_path, 'r'))
FileNotFoundError: [Errno 2] No such file or directory: 'bdd100k/labels/bdd100k_labels_images_train.json'
do you have other methods? thanks

**Comment by sabipeople** [comment]
error type seems to be different from the first one you ask.
are you sure that the file exist in the path ? i mean the json file.
it seems the code telling you that you don't have the json file in that path.
describe your directory structure plz.

**Comment by EvaneSnow** [comment]
@sabipeople the json file exist in the path, I copy the root;

**Comment by pushgct** [comment]
I gave all the files necessary in respective folders- images and json. Yet i get following error on execution:
show_labels.py:15: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import Iterable
Image: 0000f77c-6257be58.jpg
Traceback (most recent call last):
  File "show_labels.py", line 881, in <module>
    main()
  File "show_labels.py", line 877, in main
    viewer.view()
  File "show_labels.py", line 547, in view
    self.show()
  File "show_labels.py", line 560, in show
    self.show_image()
  File "show_labels.py", line 667, in show_image
    if 'cali' in frame['intrinsics']:
KeyError: 'intrinsics'
