### ISSUE TITLE
Error running show.labels.py

### ISSUE THREAD

**Issue by pushgct** [ucbdrive/bdd-data#65]
When I execute show.labels.py, I get following warning and error:
show_labels.py:15: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import Iterable
usage: show_labels.py [-h] [-i IMAGE] [--image-dir IMAGE_DIR] -l LABEL
                      [-s SCALE] [--no-attr] [--no-lane] [--no-drivable]
                      [--no-box2d] [-o OUTPUT_DIR] [--instance] [--drivable]
                      [--target-objects TARGET_OBJECTS] [--format FORMAT]
show_labels.py: error: the following arguments are required: -l/--label

I am assuming the warning can be ignored as my Python version is 3.7. Please help with the error.

**Comment by pushgct** [comment]
with the below command :
python3 show_labels.py --image-dir train/ -l data/bdd100k_labels_images_train.json

The Images are in train directory and json is present in data directory. Im in urgent need to resolve this please.
I get following error:
show_labels.py:15: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import Iterable
Image: 0000f77c-6257be58.jpg
Traceback (most recent call last):
  File "show_labels.py", line 881, in <module>
    main()
  File "show_labels.py", line 877, in main
    viewer.view()
  File "show_labels.py", line 547, in view
    self.show()
  File "show_labels.py", line 560, in show
    self.show_image()
  File "show_labels.py", line 667, in show_image
    if 'cali' in frame['intrinsics']:
KeyError: 'intrinsics'

**Comment by fyu** [comment]
Thanks for letting us know the error. It is fixed in #67
